apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: cortex-security-lab-app
  namespace: cortex-security-lab

  annotations:
    alb.ingress.kubernetes.io/scheme: internet-facing

    # Directly register Pod IPs in the ALB target group.
    alb.ingress.kubernetes.io/target-type: ip

    # Security lab: expose HTTP publicly.
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTP":80}]'

    alb.ingress.kubernetes.io/healthcheck-path: /
    alb.ingress.kubernetes.io/success-codes: "200-399"

spec:
  ingressClassName: alb

  rules:
    - http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: cortex-security-lab-app
                port:
                  number: 80
